#!/usr/bin/bash -i

###############################################
# Installing miniconda and bioconda packages
#
# by LC, 2018 
#


APPNAME=${APPNAME:-miniconda}
VERSION=${VERSION:-3}
INSTALL_PREFIX=${INSTALL_PREFIX:-/shared/ucl/depts/cancer/apps/$APPNAME/}
MD5=${MD5:-REPLACE}
SHA1=${SHA1:-REPLACE}
SRC_ARCHIVE=${SRC_ARCHIVE:-https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh}

set -e

export PATH=$INSTALL_PREFIX:$PATH

mkdir -p $INSTALL_PREFIX
rm -rf ${INSTALL_PREFIX}/${VERSION}
mkdir -p ${INSTALL_PREFIX}/${VERSION}
cd $INSTALL_PREFIX


wget -N $SRC_ARCHIVE
bash Miniconda3-latest-Linux-x86_64.sh


